// Get action

export const GET_PRODUCT_PROGRESS="GET_PRODUCT_PROGRESS"
export const GET_PRODUCT_ERROR="GET_PRODUCT_ERROR"
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"


// Post action

export const POST_PRODUCT_PROGRESS="POST_PRODUCT_PROGRESS"
export const POST_PRODUCT_ERROR="POST_PRODUCT_ERROR"
export const POST_PRODUCT_SUCCESS="POST_PRODUCT_SUCCESS"

//delete action
export const DELETE_PRODUCT_DELETE="DELETE_PRODUCT_DELETE"


